### ISSUE TITLE
Run Scheduled jobs only in certain environments fails. If scheduled jobs yml file is blank

### ISSUE THREAD

**Issue by davidtolsma** [mattyr/sidecloq#35]
Rails (5.2) environment 

# config/sidecloq.yml
development: &default

test: 
  <<: *default

staging:
  <<: *default

production:
   update_system:
      class: UpdateSystemJob
      cron: "* 18 * * *"

Since development environment i don't want to run scheduler. When i startup sidekiq process in dev, it throws this error. 
sidecloq-0.4.8/lib/sidecloq/schedule.rb:15:in `from_yaml'
from_hash(YAML.load_file(filename))

Is there a way i can only have some environments run a scheduled jobs and the others are blank?

**Comment by mattyr** [comment]
When I want to not have the scheduler actually schedule anything, I'll typically just use an impossible cron line -- like `0 5 31 2 *`, which makes the job viewable (and triggerable) by the web interface, but not via the scheduler (since that time doesn't exist).  Another option is to pass an empty hash as the schedule in the config, ie:

```ruby
Sidecloq.configure do |config|
   config[:schedule] = Sidecloq::Schedule.new({}) unless Rails.env.production?
end
```

From your error, it may make sense to make 2 changes to sidecloq:

- Make running configurable (ie, ```Sidecloq.enabled = false```)
- Don't raise an error for empty configurations

I can probably take care of these some time soon, but in the meantime you can use my workarounds above (which will remain compatible even after the above changes are made)

**Comment by davidtolsma** [comment]
Thanks, i'll use the workaround until then.

**Comment by mattyr** [comment]
Actually, can you share the full error, and the raw config file?  I'm actually wondering if there's a syntax error or if the parsing inside of Sidecloq needs adjustment...

**Comment by davidtolsma** [comment]
if there is no development environment in the yml file will it work? 

because i think the issue is: from_hash(YAML.load_file(filename)) is nil

**Comment by mattyr** [comment]
Yeah that's one thing I'm trying to parse out.  Your config file in a raw-er form would help!

**Comment by davidtolsma** [comment]
[sidecloq.yml.txt](https://github.com/mattyr/sidecloq/files/3788715/sidecloq.yml.txt)

I've tried a few iterations and they all fail when starting sidekiq. The attached file (renamed with .txt so github would allow me to upload) is the final form i want to accomplish. 

```
development: &development

test: 
  <<: *development

staging: &default
  update_system:
    class: UpdateSystemJob 
    cron: "* 18 * * *" 

production:
  <<: *default
```

**Comment by mattyr** [comment]
ahh, so I think it may be a YAML syntax issue here.  your development section results in a `null` rather than an empty mapping, and then not extending the reference in the test section results in a mapping of `<<` to `null`.  so i think that the error raised should remain (though i admit it is a little hard to decipher) -- it's pointing out that the schedule file isn't a good format.  To fix your issues, but keep using references as you are, you'll have to mix in some YAML flow syntax and update the test reference.  This should work:

```yaml
development: &development {}

test: *development

staging: &default
  update_system:
    class: UpdateSystemJob 
    cron: "* 18 * * *" 

production: *default
```

(note the empty mappings in development, and the direct reference for production/test rather than the extension reference).

Cheers!

**Comment by davidtolsma** [comment]
Ideally, for an Enhancement request. if i could just provide the environments that i want a schedule job to run, that would be even better.

```
production:
  update_system:
    class: UpdateSystemJob 
    cron: "* 18 * * *" 
```

the development, test, and other environments would be missing from the yaml.
